[package]
name = "emacs-rust-module"
version = "0.1.0"
authors = ["Sebastian Wiesner <swiesner@lunaryorn.com>"]
build = "build.rs"

[build-dependencies]
bindgen = "*"
hyper = { version = "0.9", default-features = false, features = ["security-framework"] }

[lib]
crate-type = ["cdylib"]
